<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_Master_fasilitas extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fasilitas_model');
        $this->load->library('form_validation');
		
		$this->load->model('Cleaning_service_model');
    }

    public function index()
    {
        $c_master_fasilitas = $this->Fasilitas_model->get_all();

        $data = array(
            'c_master_fasilitas_data' => $c_master_fasilitas
        );

        $this->load->view('AdmindanUser/header', $data);
        $this->load->view('master_fasilitas/fasilitas_list', $data);
        $this->load->view('AdmindanUser/footer', $data);
    }

    public function read($id) 
    {
        $row = $this->Fasilitas_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID_FASILITAS' => $row->ID_FASILITAS,
		'ID_RUANGAN' => $row->ID_RUANGAN,
		'FASILITAS' => $row->FASILITAS,
	    );
			$this->load->view('AdmindanUser/header', $data);
            $this->load->view('master_fasilitas/fasilitas_read', $data);
			$this->load->view('AdmindanUser/footer', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('c_master_fasilitas'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('c_master_fasilitas/create_action'),
	    'ID_FASILITAS' => set_value('ID_FASILITAS'),
	    'ID_RUANGAN' => $this->Fasilitas_model->get_ambil_ruangan(),
	    'FASILITAS' => set_value('FASILITAS'),
	);
		$this->load->view('AdmindanUser/header', $data);
        $this->load->view('master_fasilitas/fasilitas_form', $data);
		$this->load->view('AdmindanUser/footer', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'ID_FASILITAS' => $this->Fasilitas_model->getkodeunik(),
		'ID_RUANGAN' => $this->input->post('ID_RUANGAN',TRUE),
		'FASILITAS' => $this->input->post('FASILITAS',TRUE),
	    );

            $this->Fasilitas_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('c_master_fasilitas'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Fasilitas_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('c_master_fasilitas/update_action'),
		'ID_FASILITAS' => set_value('ID_FASILITAS', $row->ID_FASILITAS),
		'ID_RUANGAN' => set_value('ID_RUANGAN', $row->ID_RUANGAN),
		'FASILITAS' => set_value('FASILITAS', $row->FASILITAS),
	    );
			$this->load->view('AdmindanUser/header', $data);
            $this->load->view('master_fasilitas/fasilitas_form', $data);
			$this->load->view('AdmindanUser/footer', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('c_master_fasilitas'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID_FASILITAS', TRUE));
        } else {
            $data = array(
		'ID_RUANGAN' => $this->input->post('ID_RUANGAN',TRUE),
		'FASILITAS' => $this->input->post('FASILITAS',TRUE),
	    );

            $this->Fasilitas_model->update($this->input->post('ID_FASILITAS', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('c_master_fasilitas'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Fasilitas_model->get_by_id($id);

        if ($row) {
            $this->Fasilitas_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('c_master_fasilitas'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('c_master_fasilitas'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('ID_RUANGAN', 'id ruangan', 'trim|required');
	$this->form_validation->set_rules('FASILITAS', 'fasilitas', 'trim|required');

	$this->form_validation->set_rules('ID_FASILITAS', 'ID_FASILITAS', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file c_master_fasilitas.php */
/* Location: ./application/controllers/c_master_fasilitas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-30 04:24:28 */
/* http://harviacode.com */