<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class C_Master_ruangan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Master_ruangan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $c_master_ruangan = $this->Master_ruangan_model->get_all();

        $data = array(
            'c_master_ruangan_data' => $c_master_ruangan
        );

        $this->load->view('AdmindanUser/header', $data);
        $this->load->view('master_ruangan/master_ruangan_list', $data);
        $this->load->view('AdmindanUser/footer', $data);
    }

    public function read($id) 
    {
        $row = $this->Master_ruangan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'ID_RUANGAN' => $row->ID_RUANGAN,
		'NAMA_RUANGAN' => $row->NAMA_RUANGAN,
	    );
			$this->load->view('AdmindanUser/header', $data);
            $this->load->view('master_ruangan/master_ruangan_read', $data);
			$this->load->view('AdmindanUser/footer', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('c_master_ruangan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('c_master_ruangan/create_action'),
	    'ID_RUANGAN' => set_value('ID_RUANGAN'),
		//$data['kodeunik'] = $this->Master_ruangan_model->getkodeunik($table);
	    'NAMA_RUANGAN' => set_value('NAMA_RUANGAN'),
	);
		$this->load->view('AdmindanUser/header', $data);
        $this->load->view('master_ruangan/master_ruangan_form', $data);
		$this->load->view('AdmindanUser/footer', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'ID_RUANGAN' => $this->Master_ruangan_model->getkodeunik(),
		'NAMA_RUANGAN' => $this->input->post('NAMA_RUANGAN',TRUE),
	    );

            $this->Master_ruangan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('c_master_ruangan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Master_ruangan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('c_master_ruangan/update_action'),
		'ID_RUANGAN' => set_value('ID_RUANGAN', $row->ID_RUANGAN),
		'NAMA_RUANGAN' => set_value('NAMA_RUANGAN', $row->NAMA_RUANGAN),
	    );
			$this->load->view('AdmindanUser/header', $data);
            $this->load->view('c_master_ruangan/master_ruangan_form', $data);
			$this->load->view('AdmindanUser/footer', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('c_master_ruangan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('ID_RUANGAN', TRUE));
        } else {
            $data = array(
		'NAMA_RUANGAN' => $this->input->post('NAMA_RUANGAN',TRUE),
	    );

            $this->Master_ruangan_model->update($this->input->post('ID_RUANGAN', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('c_master_ruangan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Master_ruangan_model->get_by_id($id);

        if ($row) {
            $this->Master_ruangan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('c_master_ruangan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('c_master_ruangan'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('NAMA_RUANGAN', 'nama ruangan', 'trim|required');

	$this->form_validation->set_rules('ID_RUANGAN', 'ID_RUANGAN', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file C_Master_ruangan.php */
/* Location: ./application/controllers/C_Master_ruangan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-28 05:21:41 */
/* http://harviacode.com */