<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Fasilitas_model extends CI_Model
{

    public $table = 'fasilitas';
    public $id = 'ID_FASILITAS';
    public $order = 'DESC';
	var $tabel_ruangan='master_ruangan';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('fasilitas.*, master_ruangan.NAMA_RUANGAN');
		$this->db->from('fasilitas');
		$this->db->join('master_ruangan','fasilitas.ID_RUANGAN=master_ruangan.ID_RUANGAN','');
        return $this->db->get()->result();
    }
	function getkodeunik() {
	$q = $this->db->query("SELECT MAX(RIGHT(ID_FASILITAS,3)) AS idmax FROM fasilitas"); 
	$kd = ""; //kode awal
		if($q->num_rows()>0){ //jika data ada 
			foreach($q->result() as $k){ 
				$tmp = ((int)$k->idmax)+1; //string kode diset ke integer dan ditambahkan 1 dari kode terakhir 
				$kd = sprintf("%03s", $tmp); //kode ambil 4 karakter terakhir 
			} 
		}else{ //jika data kosong diset ke kode awal 
			$kd = "001"; 
		} 
		//$kar = "R."; //karakter depan kodenya //gabungkan string dengan kode yang telah dibuat tadi 
		return "F".$kd; 
	} 
	
	public function get_ambil_ruangan() {
	//$this->db->where($this->user_group, $this->group)
	$sql_ruangan=$this->db->get($this->tabel_ruangan);	
	if($sql_ruangan->num_rows()>0){
		foreach ($sql_ruangan->result_array() as $row)
			{
				$result['-']= '- Pilih Ruangan -';
			$result[$row['ID_RUANGAN']]= ($row['NAMA_RUANGAN']);
			}
			return $result;
		}
	}

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_FASILITAS', $q);
	$this->db->or_like('ID_RUANGAN', $q);
	$this->db->or_like('FASILITAS', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_FASILITAS', $q);
	$this->db->or_like('ID_RUANGAN', $q);
	$this->db->or_like('FASILITAS', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Fasilitas_model.php */
/* Location: ./application/models/Fasilitas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-30 04:24:28 */
/* http://harviacode.com */