<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master_ruangan_model extends CI_Model
{

    public $table = 'master_ruangan';
    public $id = 'ID_RUANGAN';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
	/* function getkodeunik(){
		$this->db->select('RIGHT(master_ruangan.ID_RUANGAN,6) as kode', FALSE);
		$this->db->order_by('ID_RUANGAN','DESC');
		$this->db->limit(1);
		$query = $this->db->get('master_ruangan');
		//cek dulu apakah ada sudah ada kode di tabel.
		if($query->num_rows() <> 0){
			//jika kode ternyata sudah ada.
			$data = $query->row();
			$kode = intval($data->kode) + 1;
		}else{
			//jika kode belum ada
			$kode = 1;
		}
		$kodemax = str_pad($kode, 6, "0", STR_PAD_LEFT);
		$kodejadi = "PNJ".$kodemax;
		return $kodejadi;
	} */
	function getkodeunik() {
	$q = $this->db->query("SELECT MAX(RIGHT(ID_RUANGAN,3)) AS idmax FROM master_ruangan"); 
	$kd = ""; //kode awal
		if($q->num_rows()>0){ //jika data ada 
			foreach($q->result() as $k){ 
				$tmp = ((int)$k->idmax)+1; //string kode diset ke integer dan ditambahkan 1 dari kode terakhir 
				$kd = sprintf("%03s", $tmp); //kode ambil 4 karakter terakhir 
			} 
		}else{ //jika data kosong diset ke kode awal 
			$kd = "001"; 
		} 
		//$kar = "R."; //karakter depan kodenya //gabungkan string dengan kode yang telah dibuat tadi 
		return "R".$kd; 
	} 

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_RUANGAN', $q);
	$this->db->or_like('NAMA_RUANGAN', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_RUANGAN', $q);
	$this->db->or_like('NAMA_RUANGAN', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Master_ruangan_model.php */
/* Location: ./application/models/Master_ruangan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-09-28 05:21:41 */
/* http://harviacode.com */