<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Master_Tugas_model extends CI_Model
{

    public $table = 'tugas';
    public $id = 'ID_TUGAS';
    public $ID_RUANGAN = 'ID_RUANGAN';
    public $order = 'DESC';
	var $tabel_fasilitas='fasilitas';
	var $tabel_ruangan='master_ruangan';

    function __construct()
    {
        parent::__construct();
    }
	
	public function simpan(){
		$data_laporan=array(
			'ID_TUGAS'=>$this->Master_Tugas_model->getkodeunik(),
			'ID_RUANGAN'=>$this->input->post('id_ruangan'),
			'ID_FASILITAS'=>$this->input->post('id_fasilitas'),
			'JENIS_TUGAS'=>$this->input->post('jenis_tugas')
		);	
		$this->db->insert($this->table,$data_laporan);	
	}

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
	
	function getkodeunik() {
	$q = $this->db->query("SELECT MAX(RIGHT(ID_TUGAS,3)) AS idmax FROM tugas"); 
	$kd = ""; //kode awal
		if($q->num_rows()>0){ //jika data ada 
			foreach($q->result() as $k){ 
				$tmp = ((int)$k->idmax)+1; //string kode diset ke integer dan ditambahkan 1 dari kode terakhir 
				$kd = sprintf("%03s", $tmp); //kode ambil 4 karakter terakhir 
			} 
		}else{ //jika data kosong diset ke kode awal 
			$kd = "001"; 
		} 
		//$kar = "R."; //karakter depan kodenya //gabungkan string dengan kode yang telah dibuat tadi 
		return "T".$kd; 
	} 
	
	public function ambil_ruangan() {
	$sql_ruangan=$this->db->get($this->tabel_ruangan);	
	if($sql_ruangan->num_rows()>0){
		foreach ($sql_ruangan->result_array() as $row)
			{
				$result['-']= '- Pilih Ruangan -';
				$result[$row['ID_RUANGAN']]= ucwords(strtolower($row['NAMA_RUANGAN']));
			}
			return $result;
		}
	}
	
	public function ambil_fasilitas($kode_ruangan) {
	//$this->db->where($this->user_group, $this->group)
	$this->db->where('ID_RUANGAN',$kode_ruangan);
	$this->db->order_by('fasilitas','asc');
	$sql_fasilitas=$this->db->get($this->tabel_fasilitas);	
	if($sql_fasilitas->num_rows()>0){
		foreach ($sql_fasilitas->result_array() as $row)
			{
				$result['-']= '- Pilih Fasilitas -';
			$result[$row['ID_FASILITAS']]= ucwords(strtolower($row['FASILITAS']));
			}
			return $result;
		}
	}

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID_TUGAS', $q);
	$this->db->or_like('ID_FASILITAS', $q);
	$this->db->or_like('JENIS_TUGAS', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID_TUGAS', $q);
	$this->db->or_like('ID_FASILITAS', $q);
	$this->db->or_like('JENIS_TUGAS', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Master_Tugas_model.php */
/* Location: ./application/models/Master_Tugas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-01 04:43:04 */
/* http://harviacode.com */